name: Test and Package

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  create:
    tags:
      "*"

env:
   DOCKER_IMAGE: apps-web
   PROJECT_ID: ${{ secrets.GPC_PROJECT_ID }}
   SERVICE_ACCOUNT: ${{ secrets.GPC_SERVICE_ACCOUNT }}
   WORKLOAD_PROVIDER: ${{ secrets.GPC_WORKLOAD_PROVIDER }}
   
jobs:

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Install Dependencies
      run: |
        npm install .
    
    - name: Test
      run: |
        npx vitest --run

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    
    runs-on: ubuntu-22.04

    needs: test

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - uses: actions/checkout@v3

    - id: getTag
      name: Extract the tag of the Docker image
      run: |
         VERSION=$(git describe --tags --abbrev=0)
         echo "::set-output name=tag::${VERSION}"

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v0
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.GPC_WORKLOAD_PROVIDER }}
        service_account: ${{ secrets.GPC_SERVICE_ACCOUNT }}@${{ secrets.GPC_PROJECT_ID }}.iam.gserviceaccount.com
        access_token_lifetime: 300s

    - name: Login to Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: europe-north1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: docker-push-tagged
      name: Tag Docker image and push to Google Artifact Registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |
             europe-north1-docker.pkg.dev/${{ secrets.GPC_PROJECT_ID }}/ax-repo/apps-web:${{ steps.getTag.outputs.tag }}
             europe-north1-docker.pkg.dev/${{ secrets.GPC_PROJECT_ID }}/ax-repo/apps-web:latest
